output.elasticsearch:
    enabled: true
    hosts: ["http://elasticsearch:9200"]
filebeat.prospectors:
  - type: log
    enabled: true
    paths:
        - /logs/spring-boot-logging.log
    multiline.pattern: ^\{
    multiline.negate: true
    multiline.match: after
setup.kibana:
   host: "http://kibana:5601"
setup.template.enabled: false
processors:
 - decode_json_fields:
     fields: ["message"]
     process_array: false
     max_depth: 1
     target: ""
     overwrite_keys: true